### ISSUE TITLE
ModBus? TTL to RS485 converter?

### ISSUE THREAD

**Issue by seramonte** [maxzerker/PZEM-017-v1#2]
Thank you for the code, but it is not working for me. I have used pzem-004tv3 module and related code with arduino Uno and it works great. 

I'm trying to talk to Arduino Uno, and need (I believe) TTL to rs485 translation. Would you describe how this code is intended to work with pzem-017 module (and arduino Uno)? For example, Modbus library is apparently not used; is the code performing some of those tasks? Also, is a TTL to rs485 module needed? If so, which type is presumed, 2-pin (A,B) or 4-pin (DI,DE,RE,RO)? Thanks.

**Comment by seramonte** [comment]
I'm using XY-017  ttl-rs485 converter: https://www.aliexpress.com/item/32431974521.html

I tried your code on an Arduino Due; it compiles but does nothing, prints nothing. If I comment out:
PZEM017v1 pzem(&Serial3, 0x01);
it at least prints messages to Serial. Seems like something in the .cpp file, but no errors. There is this warning: 

PZEM-017-v1-master/PZEM017v1.cpp:123:22: warning: deleting object of abstract class type 'Stream' which has non-virtual destructor will cause undefined behaviour [-Wdelete-non-virtual-dtor]
         delete this->_serial;

This occurs on Uno and Due.

**Comment by seramonte** [comment]
I verified my setup with other code base and everything works! But I am curious to get this code to work. I get this error when running the sample PZEMHardSerial.ino:

`.arduino15/packages/arduino/hardware/sam/1.6.12/variants/arduino_due_x/variant.h:251:18: error: 'Serial' has a previous declaration as 'UARTClass Serial'
 extern UARTClass Serial;`

If I comment out `extern HardwareSerial Serial;` in the .cpp file, the code compiles but no lights on rs485, and no debug output on Serial. Nothing.

**Comment by AquaticsLive** [comment]
I would like to know which hardware is working I may need to swap to a different Arduino or rs485 board just haven't figured out the combo that works.  I do have it working with the included software just can't get my Arduino to read the data.  My guess is that I should use the rs485 that doesn't have those enable pins but wanted to ask.  I have a Mega, Uno, and ESP32.

**Comment by AquaticsLive** [comment]
Answering my own issue I read through the code and there is no flow control setup.  So I am ordering a 485 adapter with automatic flow control.  Makes sense too since each serial transmit maybe a little faster or slower my Arduino boards don't seem to be precise enough for doing flow control trying to time out the enable of transit or receive seems to be a battle that I can't figure out on my scope I see the timing of the edge of the code seems to not be the same between attempts to send. I gave up on trying to adapt the code to work with the MAX485 that doesn't have automatic flow control.  I will come back here and add a comment to say how it's going after I get the new boards being more exact for my future self or others this is the title from Amazon "SongHe TTL to RS485 Module 485 to Serial UART Level Mutual Conversion Hardware Automatic Flow Control Module 3.3V 5.0V Power Supply Long Distance Transmission（5pcs)"  Aric-AquaticsLive

**Comment by AquaticsLive** [comment]
I got the auto flow control boards today and hooked up and bingo everything works.  Also, have to love the TX and RX LEDs on the board.  Swapped in each of my different Arduino boards and they all worked.   So to help others that are trying to debug things I used an MQTT sketch for the boards that had wifi which is super nice to read serial at least to my Windows PC using MQTT box App without having to use software serial.  Now my old Uno board what I did first was have it blink the LED if it received data, then I used a display sketch to read one value.  That confirmed to me that it works everywhere and could help others figure out their issue.  For me, the auto flow control rs485 adapter was the magic and of course, the super clean code of maxzerker is a perfect combo so much easier to understand what is going on than using the regular Modbus code and the MAX485.

**Comment by maxzerker** [comment]
![image](https://user-images.githubusercontent.com/24807094/109607012-1ab0ce80-7b5a-11eb-8c3e-582e2f1d0021.png)
Sorry for late reply get above TTL converter and you life will be much easier!

**Comment by maxzerker** [comment]
![image](https://user-images.githubusercontent.com/24807094/109607012-1ab0ce80-7b5a-11eb-8c3e-582e2f1d0021.png)
Sorry for late reply, I'm using above rs485 TTL on this project.

**Comment by AquaticsLive** [comment]
![61jsYiEs7xL _SL1010_](https://user-images.githubusercontent.com/10359111/109670805-1b853880-7b39-11eb-8ee6-4ccc52034213.jpg)

**Comment by AquaticsLive** [comment]
That is the one I am using so pretty much the same just without the holes populated.
